/*
 *
 * Module:    HomeAssistant
 * Package:   Main
 * Component: ConceptualLogicalEntities
 *
 * Registers a logical device's own capabilities (integration_logical_storage.go's
 * TLogicalCapability) once Conceptual.def positions/references them -- the "logical" kind's own
 * counterpart to registerDiscoveryAvailabilityEntityLink/registerDeviceSourceEntityLink. Two
 * capability shapes exist today (see integration_logical_storage.go's own header comment for the
 * full grammar): an IsAvailable condition (registerLogicalIsAvailableCapability) and a media_player
 * -> switch coercion (registerLogicalMediaSwitchCapability). A logical capability's own
 * Entity/EnablerEntity are always literal, already-existing HA entity_ids -- nothing to wait on --
 * but switch.media's own reverse lookup of its sibling "node" capability's resolved entity_id CAN
 * need to defer (2026-09-24, real bug found live): registerDevicePositioning still auto-registers
 * "node" first, synchronously, but "node" itself may now resolve via a Logical.def override whose
 * own condition auto-materializes a same-device "local" sibling positioned by a LATER line in the
 * same block -- see registerLogicalMediaSwitchCapability's own doc comment for the full story.
 *
 * Every capability shape here materializes its own generator-authored entity (a condition-based
 * template sensor, an input_number helper, a media_player->switch coercion) -- never something
 * assumed to already exist externally -- so each AppendEntityRecord call below sets
 * HasDefinitionOrImport: true (main_entities.go's own kind-5 "assumed to exist on main" collector,
 * collectMainEntityIDs, sweeps in anything left false). Real bug found live 2026-09-21: this was
 * missing on all four, so any such capability positioned WITHOUT going through a real Conceptual.def
 * "entity ...;" body line (Physical.def's own separate hasDefOrImport computation never runs in that
 * case) -- e.g. a device's own default/implicit "node" capability, auto-registered straight through
 * this same dispatch by registerDevicePositioning -- got spuriously flagged as
 * "confirmed not to exist on main" the moment the coordinator checked it, even though it's about to
 * be generated by this very run. Silent until now only because every prior case (windy/sunny/
 * daylight/battery_alert) happened to already be deployed and thus genuinely present by the time
 * anyone checked; Vienna's new environment.weather "node" capability was the first one caught before
 * its first deploy.
 *
 * Creator: Henderik A. Proper (e.proper@acm.org), Junglinster, Luxembourg, in collaboration with Claude.ai
 *
 * Version of: 21.09.2026
 *
 */

package main

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"
)

// registerLogicalIsAvailableCapability resolves a "<domain>.<label>: <entity> is available [with:
// enabler <entity-ref>; delay_off <time>; end;];" capability into a plain condition-based entity,
// reusing the exact same TEntityRecord/buildConditionBinarySensorYAML pipeline
// registerDiscoveryAvailabilityEntityLink already relies on -- no new YAML rendering needed at
// all. Both Entity and EnablerEntity are literal, already-existing HA entity_ids (never a
// space-relative DSL spec -- Logical.def has no space nesting of its own to resolve one against),
// used verbatim as Jinja states()/is_state() arguments, exactly like the hassbridge/hosts "<entity>
// is available;" sugar already does elsewhere in this codebase.
//
// EnablerEntity, and (2026-09-16) every "dependency on <id>;" target's own node entity_id
// (resolveLogicalDependencyNodeEntities), are folded into ConditionExpr as literal Go-formatted
// strings, NOT as further "$N" placeholders -- real bug found live 2026-09-16: buildConditionStateExpr
// substitutes EVERY "$N" with sourceToJinja2(source), which always wraps in a states(...) call
// (right for "$1 not in [...]", which wants a VALUE, but wrong for is_state('$2', 'off'), which
// wants $2 to be the BARE entity_id string is_state()'s own first argument expects) -- produced the
// doubly-wrapped, syntactically broken "is_state('states(\'switch...\')', 'off')" the one time this
// ran against a real enabler. Both EnablerEntity and each dependency's own resolved entity_id are
// already plain, fully-resolved literals by the time this function sees them, so embedding them
// directly via fmt.Sprintf is correct and simpler than trying to make the shared $-substitution
// mechanism support a second, differently-shaped placeholder convention.
//
// Ordering, per the user's own explicit design (2026-09-16, retrofitting appliance.apple_tv/
// appliance.tv's own dependency on node.appletv/node.tv, generalizing to appliance.sonos's two
// dependencies): every "dependency on" target is AND-ed into the base $1-not-unavailable check
// FIRST, and the enabler's own OR only nuances that already-AND-ed result -- so an enabler being
// off ALWAYS wins (the user has manually indicated the device isn't in use), even if a dependency
// is itself unreachable.
func registerLogicalIsAvailableCapability(administration *TAdministrationState, decl TDeviceCapabilityEntityDeclaration, capability TLogicalCapability, label, deviceNamePath, entitiesPath string, lineNum int, hostDevicesByID map[string]THostDevice) []string {
	provenance := fmt.Sprintf("%s:%d → %s from %s %s", filepath.Base(entitiesPath), lineNum, decl.LocalSpec, decl.DeviceID, decl.Capability)

	fullName := resolveDeviceEntityFullName(decl.LocalSpec, administration.SpacePath, deviceNamePath)
	identity := extractEntityIdentity(fullName)
	if identity.Domain == "" {
		return []string{fmt.Sprintf("%s: could not resolve a domain from %q; skipping", provenance, decl.LocalSpec)}
	}
	entityID := toHomeAssistantEntityID(fullName)
	if entityID == "" {
		return []string{fmt.Sprintf("%s: could not resolve a Home Assistant entity id from %q; skipping", provenance, decl.LocalSpec)}
	}

	dependencyEntityIDs, warnings := resolveLogicalDependencyNodeEntities(capability.DependsOn, hostDevicesByID, administration, provenance)

	baseParts := []string{"$1 not in ['unavailable', 'unknown']"}
	for _, depEntityID := range dependencyEntityIDs {
		baseParts = append(baseParts, fmt.Sprintf("is_state('%s', 'on')", depEntityID))
	}
	base := strings.Join(baseParts, " and ")
	expr := base
	if capability.EnablerEntity != "" {
		expr = fmt.Sprintf("(%s) or is_state('%s', 'off')", base, capability.EnablerEntity)
	}

	sources := []string{capability.Entity}
	spaceName := administration.CurrentSpaceName()
	administration.RegisterExternalEntityReference(spaceName, capability.Entity, provenance)
	if capability.EnablerEntity != "" {
		administration.RegisterExternalEntityReference(spaceName, capability.EnablerEntity, provenance)
	}
	deviceClass, _, _, icon := resolveCapabilityDefaults(administration.CapabilityDefaults, identity.Domain, identity.Path)
	administration.AppendEntityRecord(spaceName, TEntityRecord{
		Name:                  fullName,
		Identity:              identity,
		Provenance:            provenance,
		ConditionSources:      sources,
		ConditionExpr:         expr,
		ConditionDelayOff:     capability.DelayOff,
		ConditionDevClass:     deviceClass,
		EntityIcon:            icon,
		HasDefinitionOrImport: true,
	})
	administration.LogicalEntityLinks[entityID] = TLogicalEntityLink{DeviceID: decl.DeviceID, Label: label}
	return warnings
}

// registerLogicalAbsorbedCapability resolves a "<domain>.<label>: <bare-capability>;" line found
// inside a device's own "capabilities from <device-id>: ... end;" block (2026-09-18, the "absorb"
// operation -- integration_logical_storage.go's own header comment, and memory/project_logical_
// layer_device_combining.md). Unlike this file's other two capability shapes, this one computes
// NOTHING of its own: capability.AbsorbedFromDeviceID/AbsorbedFromCapability simply name another,
// already-declared device's own capability, so this just rebuilds an ordinary
// TDeviceCapabilityEntityDeclaration targeting THAT device and re-enters the normal dispatch
// (registerDeviceCapabilityEntityLinkAllowingHidden) recursively -- decl.LocalSpec and
// deviceNamePath are passed through unchanged, so the resulting entity is positioned/named as part
// of the HOST device (decl.DeviceID, e.g. "appliance.washing_machine"), even though its value comes
// from the absorbed device (e.g. "discovery.washing_machine_switch"). This can defer exactly like
// any other branch the recursive call might land in (e.g. a discovery "derived" sibling not yet
// positioned), so deferred is threaded straight back to the caller.
func registerLogicalAbsorbedCapability(administration *TAdministrationState, decl TDeviceCapabilityEntityDeclaration, capability TLogicalCapability, label, deviceNamePath string, discoveryGatewaysByID map[string]TDiscoveryGatewayDevice, hassBridgeDevicesByID map[string]THassBridgeDevice, importedDevicesByID map[string]TImportedDevice, hostDevicesByID map[string]THostDevice, commandlineDevicesByID map[string]TCommandlineDevice, localDevicesByID map[string]TLocalDevice, logicalDevicesByID map[string]TLogicalDevice, entitiesPath string, lineNum int, finalAttempt bool) (warnings []string, deferred bool) {
	absorbedDecl := TDeviceCapabilityEntityDeclaration{
		LocalSpec:  decl.LocalSpec,
		DeviceID:   capability.AbsorbedFromDeviceID,
		Capability: capability.AbsorbedFromCapability,
		NoCollect:  decl.NoCollect,
	}
	warnings, deferred = registerDeviceCapabilityEntityLinkAllowingHidden(administration, absorbedDecl, discoveryGatewaysByID, hassBridgeDevicesByID, importedDevicesByID, hostDevicesByID, commandlineDevicesByID, localDevicesByID, logicalDevicesByID, entitiesPath, lineNum, finalAttempt, deviceNamePath, false, false)
	if deferred || len(warnings) > 0 {
		return warnings, deferred
	}
	// Record a LogicalEntityLinks entry under THIS device's own id/label -- not the absorbed
	// device's own DeviceID the delegate call above used -- so a sibling "derived ... over:"
	// capability on this same host device can find an absorbed capability's own resolved
	// entity_id by the exact same reverse lookup as any other capability kind (2026-09-18, the
	// user's own explicit design: "over:" resolution must see the complete logical device,
	// absorbed capabilities included, not just IsAvailable/switch-coercion ones).
	fullName := resolveDeviceEntityFullName(decl.LocalSpec, administration.SpacePath, deviceNamePath)
	if entityID := toHomeAssistantEntityID(fullName); entityID != "" {
		administration.LogicalEntityLinks[entityID] = TLogicalEntityLink{DeviceID: decl.DeviceID, Label: label}
	}
	return warnings, deferred
}

// registerLogicalMediaSwitchCapability resolves a "switch.<label>: <media-player-entity> [with:
// no_play_input "<value>"; end;];" capability -- the same media_player->switch coercion
// Macros.def's own "media_switch" directive already performs, reusing that EXACT rendering
// wholesale: generateMediaSwitches (generator.go) already dispatches on any TEntityRecord whose
// own Identity.Domain is "switch", Identity.Path ends in "/media," and MediaSwitchPlayerName is
// set -- regardless of which registration path produced that record -- so this function only ever
// needs to build a plain TEntityRecord with those same fields (plus the new
// MediaSwitchAvailabilityEntityID, this capability's own sibling "node" capability's own resolved
// entity_id), never a bespoke YAML writer of its own. NOTE: this reuse only fires when the
// capability's own label produces a path ending in "/media" (deviceNamePath + label) -- true for
// every real case built so far ("media" is the label itself), and a natural constraint of reusing
// this exact mechanism rather than something to relax.
//
// Detected by domain mismatch (declared domain "switch," source entity's own domain
// "media_player") rather than a dedicated keyword, per the user's own framing of this as "the same
// coercion the present media_switch command already does" -- any OTHER domain mismatch (a
// coercion this codebase has no real case for yet) is rejected with a clear warning instead of
// being silently guessed at.
//
// hasNodeCapability/finalAttempt (2026-09-24, real bug found live migrating Vienna's apple_tv/tv/
// sonos/sonos_roam onto the "local" kind): the sibling "node" reverse lookup used to be
// unconditionally synchronous (this file's own header comment claimed it "never needs to defer"),
// true only while every "node" derivation resolved same-pass (a literal entity_id plus a bare
// device-id atom, both always immediately resolvable). Once a device's own "node" override
// resolves via "physical <device-id>" (auto-materializing a SAME-device "local" sibling positioned
// by a LATER line in this very "device ... with:" block), the override itself now genuinely defers
// to the end-of-file retry pass (registerLogicalNodeOverride's own ViaLogicalOverride mechanism) --
// but this function, dispatched from the device's OWN "switch.media" body line, runs during the
// FIRST pass, before that retry ever happens, so LogicalEntityLinks has no "node" entry yet and the
// availability field was silently dropped (confirmed live: Vienna's four media-switch entities lost
// their "availability:" line entirely on regenerate). Fixed the same way every other same-device
// sibling reference in this codebase already handles this: defer (no warning) while the device
// declares a "node" capability of its own, the reverse lookup hasn't resolved yet, and
// !finalAttempt -- the single end-of-file retry then runs AFTER "node"'s own deferred entry (queued
// earlier, at the device's positioning header line, so it retries first in the same ordered pass).
func registerLogicalMediaSwitchCapability(administration *TAdministrationState, decl TDeviceCapabilityEntityDeclaration, capability TLogicalCapability, label, deviceNamePath, entitiesPath string, lineNum int, hasNodeCapability, finalAttempt bool) (warnings []string, deferred bool) {
	provenance := fmt.Sprintf("%s:%d → %s from %s %s", filepath.Base(entitiesPath), lineNum, decl.LocalSpec, decl.DeviceID, decl.Capability)

	sourceDomain, _, _ := strings.Cut(capability.Entity, ".")
	if capability.Domain != "switch" || sourceDomain != "media_player" {
		return []string{fmt.Sprintf("%s: logical capability %q coerces domain %q from %q, which isn't a supported coercion yet (only switch<-media_player, the \"media_switch\" shape, is built) -- skipping", provenance, label, capability.Domain, sourceDomain)}, false
	}

	fullName := resolveDeviceEntityFullName(decl.LocalSpec, administration.SpacePath, deviceNamePath)
	identity := extractEntityIdentity(fullName)
	if identity.Domain == "" {
		return []string{fmt.Sprintf("%s: could not resolve a domain from %q; skipping", provenance, decl.LocalSpec)}, false
	}
	entityID := toHomeAssistantEntityID(fullName)
	if entityID == "" {
		return []string{fmt.Sprintf("%s: could not resolve a Home Assistant entity id from %q; skipping", provenance, decl.LocalSpec)}, false
	}

	// Reverse lookup: which entity_id did this SAME device's own "node" capability resolve to?
	// See this function's own doc comment for why it may not have resolved yet.
	var nodeEntityID string
	for id, link := range administration.LogicalEntityLinks {
		if link.DeviceID == decl.DeviceID && link.Label == "node" {
			nodeEntityID = id
			break
		}
	}
	if hasNodeCapability && nodeEntityID == "" && !finalAttempt {
		return nil, true
	}

	spaceName := administration.CurrentSpaceName()
	administration.AppendEntityRecord(spaceName, TEntityRecord{
		Name:                            fullName,
		Identity:                        identity,
		Provenance:                      provenance,
		MediaSwitchPlayerName:           capability.Entity,
		MediaSwitchNoPlayInput:          capability.NoPlayInput,
		MediaSwitchAvailabilityEntityID: nodeEntityID,
		HasDefinitionOrImport:           true,
	})
	administration.LogicalEntityLinks[entityID] = TLogicalEntityLink{DeviceID: decl.DeviceID, Label: label}
	return nil, false
}

// registerLogicalDefinedInputNumberCapability resolves a "defined <domain>.<label> with: minimum
// <val>; maximum <val>; step <val>; icon <val>; units <val>; end;" capability (2026-09-18) into an
// HA input_number HELPER entity -- no device/MQTT backing at all, so this just seeds
// TEntityRecord.InputNumberMin/Max/Step/Unit/Icon directly, the exact same fields the plain
// Conceptual-layer "entity input_number.<spec> with: minimum ...; end;" construct already
// populates (expander.go's scanInputNumberBody) -- reusing the SAME generator rendering path
// wholesale, never a bespoke input_number YAML writer of its own. Always synchronous: nothing here
// depends on any sibling capability.
func registerLogicalDefinedInputNumberCapability(administration *TAdministrationState, decl TDeviceCapabilityEntityDeclaration, capability TLogicalCapability, label, deviceNamePath, entitiesPath string, lineNum int) []string {
	provenance := fmt.Sprintf("%s:%d → %s from %s %s", filepath.Base(entitiesPath), lineNum, decl.LocalSpec, decl.DeviceID, decl.Capability)

	fullName := resolveDeviceEntityFullName(decl.LocalSpec, administration.SpacePath, deviceNamePath)
	identity := extractEntityIdentity(fullName)
	if identity.Domain == "" {
		return []string{fmt.Sprintf("%s: could not resolve a domain from %q; skipping", provenance, decl.LocalSpec)}
	}
	entityID := toHomeAssistantEntityID(fullName)
	if entityID == "" {
		return []string{fmt.Sprintf("%s: could not resolve a Home Assistant entity id from %q; skipping", provenance, decl.LocalSpec)}
	}

	spaceName := administration.CurrentSpaceName()
	administration.AppendEntityRecord(spaceName, TEntityRecord{
		Name:                  fullName,
		Identity:              identity,
		Provenance:            provenance,
		InputNumberMin:        capability.DefinedMinimum,
		InputNumberMax:        capability.DefinedMaximum,
		InputNumberStep:       capability.DefinedStep,
		InputNumberUnit:       capability.DefinedUnits,
		InputNumberIcon:       capability.DefinedIcon,
		HasDefinitionOrImport: true,
	})
	administration.LogicalEntityLinks[entityID] = TLogicalEntityLink{DeviceID: decl.DeviceID, Label: label}
	return nil
}

// isKnownDeviceID reports whether id names any already-declared device (any kind) -- used to
// recognise a bare condition/value atom naming a WHOLE OTHER DEVICE (e.g. "node.candy") as sugar
// for "that device's own node capability" (2026-09-24, folding the old device-level "dependency on
// <device-id>;" effect into an ordinary condition atom), rather than mistaking it for a literal HA
// entity_id (resolveLogicalSiblingSourceEntityID's own pre-existing literal-entity-id fallback).
func isKnownDeviceID(id string, discoveryGatewaysByID map[string]TDiscoveryGatewayDevice, hassBridgeDevicesByID map[string]THassBridgeDevice, importedDevicesByID map[string]TImportedDevice, hostDevicesByID map[string]THostDevice, localDevicesByID map[string]TLocalDevice, logicalDevicesByID map[string]TLogicalDevice) bool {
	if _, ok := discoveryGatewaysByID[id]; ok {
		return true
	}
	if _, ok := hassBridgeDevicesByID[id]; ok {
		return true
	}
	if _, ok := importedDevicesByID[id]; ok {
		return true
	}
	if _, ok := hostDevicesByID[id]; ok {
		return true
	}
	if _, ok := localDevicesByID[id]; ok {
		return true
	}
	if _, ok := logicalDevicesByID[id]; ok {
		return true
	}
	return false
}

// autoMaterializePhysicalCapability generalizes resolveLogicalDependencyNodeEntities' own
// synthetic-identity pattern (integration_logical_storage.go, pre-2026-09-24: "hosts" kind + "node"
// label only) to any physical capability referenced via a cross-device "<label> from [physical]
// <device-id>;" condition/value reference that was never explicitly positioned in Conceptual.def --
// e.g. appliance.washing_machine's own physical "node" (Physical.def's "binary_sensor.node
// sensor.bathroom_washing_machine is available;"), no longer auto-registered at positioning time
// once a Logical.def override claims that same label (Conceptual_DevicePositioning.go's override
// precedence), but still reachable this way. The synthetic identity is always
// "physical/<device-id>/<label>" (sphere "physical", path the device's own raw id --
// sanitizeObjectID collapses its "." into "_" the same way it already does for the live
// "node.candy" -> "binary_sensor.physical_node_candy_node" precedent this generalizes).
//
// Covers "hosts", "hassbridge", and "discovery" kinds (import can be added the same way once a
// real case needs it -- on-demand discipline). Mutates administration.DeviceConceptualLinks[deviceID] in place (creating it if the device
// has no positioning of its own at all yet), merging the new attribute into any EXISTING link
// rather than replacing it, so a device already positioned via its own normal Conceptual.def
// declaration keeps everything it already has.
func autoMaterializePhysicalCapability(administration *TAdministrationState, deviceID, label string, discoveryGatewaysByID map[string]TDiscoveryGatewayDevice, hassBridgeDevicesByID map[string]THassBridgeDevice, hostDevicesByID map[string]THostDevice, localDevicesByID map[string]TLocalDevice, provenance string) (entityID string, ok bool) {
	link, hasLink := administration.DeviceConceptualLinks[deviceID]
	if !hasLink || link.AttributeEntityIDs == nil {
		link.AttributeEntityIDs = map[string]TDeviceAttributeLink{}
	}
	syntheticIdentity := TEntityIdentity{Sphere: "physical", Path: deviceID}

	if host, found := hostDevicesByID[deviceID]; found {
		mat, known := MaterializationForIntegrationType(host.IntegrationType)
		if !known {
			return "", false
		}
		if label == "node" {
			nodeFullName := fmt.Sprintf("%s.%s/%s/%s", mat.NodeDomain, syntheticIdentity.Sphere, syntheticIdentity.Path, mat.NodeSuffix)
			link.NodeEntityID, link.NodeDeviceClass, link.NodeIcon = registerHostNodeAttribute(administration, mat, host, nodeFullName, "root", provenance)
			if link.HostIdentity == (TEntityIdentity{}) {
				link.HostIdentity = syntheticIdentity
			}
			administration.DeviceConceptualLinks[deviceID] = link
			return link.NodeEntityID, link.NodeEntityID != ""
		}
		if !slices.Contains(mat.AttributeNames(host), label) {
			return "", false
		}
		registerHostAttributeEntity(administration, mat, host, syntheticIdentity, "root", provenance, link, label)
		administration.DeviceConceptualLinks[deviceID] = link
		attr, found := link.AttributeEntityIDs[label]
		return attr.EntityID, found
	}

	if device, found := hassBridgeDevicesByID[deviceID]; found {
		if _, hasCap := device.Capabilities[label]; !hasCap {
			return "", false
		}
		registerHassBridgeAttributeEntity(administration, device, syntheticIdentity, "root", provenance, link, label)
		administration.DeviceConceptualLinks[deviceID] = link
		attr, found := link.AttributeEntityIDs[label]
		return attr.EntityID, found
	}

	// Discovery kind (2026-09-24, added once switch.washing_machine's own "core" -- a Zigbee2MQTT
	// plug -- turned out to be the FIRST real "from [physical] <device-id>" target, not a
	// hassbridge/hosts device as initially scoped): mirrors registerDiscoveryEntityLink's own tail
	// (fullName -> identity -> entityID -> RegisterDiscoveryImpliedEntity -> DiscoveryEntityLinks),
	// just off a synthetic identity instead of a LocalSpec-derived one -- a raw leaf capability
	// only (never AvailabilityOf/DerivedFromCapability/Hidden, same restrictions
	// registerDiscoveryEntityLink itself enforces). No DeviceConceptualLinks bookkeeping needed
	// here: a discovery-kind capability's "already positioned" check (tier 3 above) scans
	// administration.DiscoveryEntityLinks by (GatewayDeviceID, Leaf), which this call populates, so
	// a later reference finds it the same way any ordinarily-positioned discovery capability would.
	if gateway, found := discoveryGatewaysByID[deviceID]; found {
		capability, hasCap := gateway.Capabilities[label]
		if !hasCap || capability.AvailabilityOf != "" || capability.DerivedFromCapability != "" || capability.Hidden {
			return "", false
		}
		attrFullName := fmt.Sprintf("%s.%s/%s/%s", capability.Domain, syntheticIdentity.Sphere, syntheticIdentity.Path, label)
		id := toHomeAssistantEntityID(attrFullName)
		if id == "" {
			return "", false
		}
		administration.RegisterDiscoveryImpliedEntity("root", attrFullName, provenance, deviceID+"!"+label, false)
		deviceClass, unit, stateClass, icon := resolveCapabilityDefaults(administration.CapabilityDefaults, capability.Domain, label)
		administration.DiscoveryEntityLinks[id] = TDiscoveryEntityLink{
			EntityID:        id,
			GatewayDeviceID: deviceID,
			Leaf:            capability.Leaf,
			SourceDomain:    capability.SourceDomain,
			DeviceClass:     deviceClass,
			Unit:            unit,
			StateClass:      stateClass,
			Icon:            icon,
		}
		return id, true
	}

	// Local kind (2026-09-24, the Ring doorbell's own "node" -- overridden by Logical.def, so never
	// auto-registered at positioning time, only reachable this way): mirrors the discovery branch's
	// own tail exactly, off the same synthetic identity, except the "is available" shape's sibling
	// lookup goes through link.AttributeEntityIDs (a "local" device's own capabilities, unlike a
	// discovery gateway's raw leaves, always populate that same per-device map -- see
	// Conceptual_LocalEntities.go's own header comment) instead of DiscoveryEntityLinks.
	if device, found := localDevicesByID[deviceID]; found {
		capability, hasCap := device.Capabilities[label]
		if !hasCap {
			return "", false
		}
		attrFullName := fmt.Sprintf("%s.%s/%s/%s", capability.Domain, syntheticIdentity.Sphere, syntheticIdentity.Path, label)
		id := toHomeAssistantEntityID(attrFullName)
		if id == "" {
			return "", false
		}
		identity := extractEntityIdentity(attrFullName)
		if capability.AvailabilityOf != "" {
			siblingAttr, hasSibling := link.AttributeEntityIDs[capability.AvailabilityOf]
			if !hasSibling {
				return "", false
			}
			sources, expr := parseConditionDirective("condition "+siblingAttr.EntityID+" is available", nil)
			if expr == "" {
				return "", false
			}
			deviceClass, _, _, icon := resolveCapabilityDefaults(administration.CapabilityDefaults, identity.Domain, identity.Path)
			administration.AppendEntityRecord("root", TEntityRecord{
				Name:                  attrFullName,
				Identity:              identity,
				Provenance:            provenance,
				ConditionSources:      sources,
				ConditionExpr:         expr,
				ConditionDevClass:     deviceClass,
				EntityIcon:            icon,
				HasDefinitionOrImport: true,
			})
		} else {
			administration.RegisterDiscoveryImpliedEntity("root", attrFullName, provenance, deviceID+"!"+label, false)
		}
		link.AttributeEntityIDs[label] = TDeviceAttributeLink{EntityID: id, Identity: identity}
		administration.DeviceConceptualLinks[deviceID] = link
		return id, true
	}

	return "", false
}

// resolveLogicalSiblingSourceEntityID resolves one condition/value expression leaf token (a bare
// sibling capability label, or a literal "domain.path[!attribute]" entity reference) against
// deviceID's own COMPLETE logical device, checked in order (the user's own explicit design,
// 2026-09-18, extended 2026-09-24 for cross-device references): (1) unless forcePhysical,
// administration.LogicalEntityLinks (DeviceID+Label -- covers an ordinary derived/switch-coercion
// capability, another "defined" one, or one absorbed via "capabilities from ...;"); (2)
// administration.DeviceConceptualLinks[deviceID]'s own already-positioned physical entity --
// .NodeEntityID for "node" (hosts-kind), else .AttributeEntityIDs[token] (import/hassbridge-kind,
// covers e.g. sensors.vienna_terrace_wind's own imported "wind_speed"); (3) discoveryGatewaysByID
// [deviceID]'s own Capabilities[token].Leaf, reverse-looked-up against
// administration.DiscoveryEntityLinks by (GatewayDeviceID, Leaf) -- a discovery-kind device's own
// real physical presence (e.g. sensors.terrace_motion's own "illuminance"); (4) when
// allowAutoMaterialize, autoMaterializePhysicalCapability -- a genuinely never-positioned physical
// capability of an EXPLICITLY OTHER device (or the SAME device's own physical value when
// forcePhysical bypassed its Logical.def override at tier 1), auto-registered on demand.
// allowAutoMaterialize is false for an ordinary same-device sibling/jinja-source token (preserves
// every existing declaration's exact behaviour -- a genuinely missing same-device sibling still
// defers/warns, never silently auto-materializes) and true only for a "from [physical]
// <device-id>" cross-device reference or a bare recognized device-id atom (isKnownDeviceID).
//
// isLiteral=true means nothing above matched and token was used verbatim because it looks like an
// already-fully-qualified entity_id (contains a ".") -- e.g. appliance.sonos_roam's own
// "sensor.infrastructural_apartment_bedroom_sonos_battery_level", an attribute of the underlying
// media_player, not a capability of this device (2026-09-19) -- callers must register it as an
// external reference (administration.RegisterExternalEntityReference) so its own live existence
// gets tracked like any other imported/hassbridge-declared entity.
func resolveLogicalSiblingSourceEntityID(administration *TAdministrationState, deviceID, token string, forcePhysical, allowAutoMaterialize bool, discoveryGatewaysByID map[string]TDiscoveryGatewayDevice, hassBridgeDevicesByID map[string]THassBridgeDevice, hostDevicesByID map[string]THostDevice, localDevicesByID map[string]TLocalDevice, provenance string) (entityID string, ok bool, isLiteral bool) {
	if !forcePhysical {
		for id, link := range administration.LogicalEntityLinks {
			if link.DeviceID == deviceID && link.Label == token {
				return id, true, false
			}
		}
	}
	if deviceLink, hasDeviceLink := administration.DeviceConceptualLinks[deviceID]; hasDeviceLink {
		if token == "node" && deviceLink.NodeEntityID != "" {
			return deviceLink.NodeEntityID, true, false
		}
		if attr, hasAttr := deviceLink.AttributeEntityIDs[token]; hasAttr {
			return attr.EntityID, true, false
		}
	}
	if gateway, isGateway := discoveryGatewaysByID[deviceID]; isGateway {
		if siblingCapability, hasCapability := gateway.Capabilities[token]; hasCapability {
			for id, link := range administration.DiscoveryEntityLinks {
				if link.GatewayDeviceID == deviceID && link.Leaf == siblingCapability.Leaf {
					return id, true, false
				}
			}
		}
	}
	if allowAutoMaterialize {
		if id, materialized := autoMaterializePhysicalCapability(administration, deviceID, token, discoveryGatewaysByID, hassBridgeDevicesByID, hostDevicesByID, localDevicesByID, provenance); materialized {
			return id, true, false
		}
	}
	if strings.Contains(token, ".") {
		return token, true, true
	}
	return "", false, false
}

// logicalConditionResolver walks a TConditionExpr tree (logical_condition_expr.go), resolving each
// leaf's raw token via resolveLogicalSiblingSourceEntityID and rendering the whole tree into ONE
// final, fully-substituted Jinja2 expression string -- deferred/warnings mirror the pre-2026-09-24
// flat "over:"-list resolution exactly (defer with no warning while !finalAttempt, one clear
// warning per unresolved leaf once finalAttempt is true).
type logicalConditionResolver struct {
	administration        *TAdministrationState
	deviceID, label       string
	provenance            string
	finalAttempt          bool
	discoveryGatewaysByID map[string]TDiscoveryGatewayDevice
	hassBridgeDevicesByID map[string]THassBridgeDevice
	importedDevicesByID   map[string]TImportedDevice
	hostDevicesByID       map[string]THostDevice
	localDevicesByID      map[string]TLocalDevice
	logicalDevicesByID    map[string]TLogicalDevice
	// valueMode is true for a "value" derivation (never boolean-composed -- a lone CondRef/CondJinja
	// tree, see parseValueExpr): a bare CondRef renders as its plain resolved value (sourceToJinja2:
	// states()/state_attr()), not the boolean is_state(...) check a "condition" bare ref needs.
	valueMode bool
	deferred  bool
	warnings  []string
}

// resolveLeaf resolves an ordinary same-device sibling label or literal entity_id (a CondJinja
// source, or a CondRef with no "from" clause and not itself a recognized device id) -- never
// auto-materializes, preserving every pre-2026-09-24 declaration's exact behaviour.
func (r *logicalConditionResolver) resolveLeaf(token string) (string, bool) {
	return r.resolveTargeted(r.deviceID, token, false, false)
}

// resolveRefNode resolves a CondRef node that may carry a "from [physical] <device-id>" qualifier
// (2026-09-24) or be itself a bare, recognized device-id (sugar for "that device's own node" --
// isKnownDeviceID, folding the old device-level "dependency on <device-id>;" into an ordinary
// atom). Both forms allow auto-materialization -- see resolveLogicalSiblingSourceEntityID's own
// doc comment for why that's safe to enable only here, never for resolveLeaf's same-device path.
func (r *logicalConditionResolver) resolveRefNode(node *TConditionExpr) (string, bool) {
	targetDeviceID := r.deviceID
	label := node.Ref
	switch {
	case node.FromDeviceID != "":
		targetDeviceID = node.FromDeviceID
		// A "from"-qualified label may be written either bare ("core") or domain-prefixed
		// ("switch.core", matching how a capability line always reads in Physical.def/Logical.def
		// even though the map key itself is always the bare label -- e.g. THassBridgeCapability's
		// own Domain is a separate field from its map key) -- strip a leading "<domain>." before
		// using it as a lookup key, same map-key shape a same-device sibling label always has.
		label = bareCapabilityLabel(node.Ref)
	case isKnownDeviceID(node.Ref, r.discoveryGatewaysByID, r.hassBridgeDevicesByID, r.importedDevicesByID, r.hostDevicesByID, r.localDevicesByID, r.logicalDevicesByID):
		targetDeviceID = node.Ref
		label = "node"
	default:
		return r.resolveLeaf(node.Ref)
	}
	return r.resolveTargeted(targetDeviceID, label, node.ForcePhysical, true)
}

// bareCapabilityLabel strips a leading "<domain>." from a "from"-qualified ref, if present --
// "switch.core" -> "core", bare "node" -> "node" unchanged.
func bareCapabilityLabel(ref string) string {
	if idx := strings.Index(ref, "."); idx > 0 {
		return ref[idx+1:]
	}
	return ref
}

func (r *logicalConditionResolver) resolveTargeted(targetDeviceID, label string, forcePhysical, allowAutoMaterialize bool) (string, bool) {
	entityID, ok, isLiteral := resolveLogicalSiblingSourceEntityID(r.administration, targetDeviceID, label, forcePhysical, allowAutoMaterialize, r.discoveryGatewaysByID, r.hassBridgeDevicesByID, r.hostDevicesByID, r.localDevicesByID, r.provenance)
	if !ok {
		if !r.finalAttempt {
			r.deferred = true
			return "", false
		}
		what := label
		if targetDeviceID != r.deviceID {
			what = fmt.Sprintf("%s from %s", label, targetDeviceID)
		}
		r.warnings = append(r.warnings, fmt.Sprintf("%s: %q has no positioning yet -- add one (any space) before referencing it from %q's own condition/value expression", r.provenance, what, r.label))
		return "", false
	}
	if isLiteral {
		r.administration.RegisterExternalEntityReference(r.administration.CurrentSpaceName(), entityID, r.provenance)
	}
	return entityID, true
}

// render returns node's own fully-substituted Jinja2 text. ok=false means resolution failed --
// check r.deferred (retry later) vs r.warnings (a real, final problem) to see which.
func (r *logicalConditionResolver) render(node *TConditionExpr) (string, bool) {
	if node == nil || r.deferred {
		return "", false
	}
	switch node.Kind {
	case CondRef:
		entityID, ok := r.resolveRefNode(node)
		if !ok {
			return "", false
		}
		if node.IsAvailable {
			return fmt.Sprintf("(states('%s') not in ['unavailable', 'unknown'])", entityID), true
		}
		if r.valueMode {
			return sourceToJinja2(entityID), true
		}
		return fmt.Sprintf("is_state('%s', 'on')", entityID), true
	case CondJinja:
		sources := make([]string, 0, len(node.JinjaSources))
		for _, token := range node.JinjaSources {
			entityID, ok := r.resolveLeaf(token)
			if !ok {
				return "", false
			}
			sources = append(sources, entityID)
		}
		return "(" + buildConditionStateExpr(sources, node.JinjaExpr) + ")", true
	case CondNot:
		child, ok := r.render(node.Child)
		if !ok {
			return "", false
		}
		return "(not " + child + ")", true
	case CondAnd:
		left, ok := r.render(node.Left)
		if !ok {
			return "", false
		}
		right, ok := r.render(node.Right)
		if !ok {
			return "", false
		}
		return "(" + left + " and " + right + ")", true
	case CondOr:
		left, ok := r.render(node.Left)
		if !ok {
			return "", false
		}
		right, ok := r.render(node.Right)
		if !ok {
			return "", false
		}
		return "(" + left + " or " + right + ")", true
	}
	return "", false
}

// registerLogicalDerivedConditionCapability resolves a "derived <domain>.<label> with:
// condition <bool-expr>; ... end;" (binary_sensor domain) or "value <atom>; ... end;" (any other
// domain) capability (2026-09-18, boolean+jinja grammar redesigned 2026-09-24 -- see
// logical_condition_expr.go's header comment for the full grammar and rationale) into ONE fully-
// resolved Jinja2 expression, stored straight into TEntityRecord.ConditionExpr with
// ConditionSources left nil -- buildConditionStateExpr (generator.go) is a verified no-op when
// sources is empty, so generateConditionEntities' existing binary_sensor/sensor domain dispatch
// needs no changes at all to render either shape.
func registerLogicalDerivedConditionCapability(administration *TAdministrationState, decl TDeviceCapabilityEntityDeclaration, capability TLogicalCapability, label, deviceNamePath, entitiesPath string, lineNum int, finalAttempt bool, discoveryGatewaysByID map[string]TDiscoveryGatewayDevice, hassBridgeDevicesByID map[string]THassBridgeDevice, importedDevicesByID map[string]TImportedDevice, hostDevicesByID map[string]THostDevice, localDevicesByID map[string]TLocalDevice, logicalDevicesByID map[string]TLogicalDevice) (warnings []string, deferred bool) {
	provenance := fmt.Sprintf("%s:%d → %s from %s %s", filepath.Base(entitiesPath), lineNum, decl.LocalSpec, decl.DeviceID, decl.Capability)

	// "condition" is reserved for binary_sensor (it's a BOOLEAN); every other domain must use
	// "value" instead -- the concrete fix for the exact bug that motivated this redesign: both
	// houses' "derived sensor.pressure with: condition "$1" over: weather.forecast!pressure; end;
	// end;" misused "condition" for a value that was never actually a boolean.
	if capability.IsDerivedCondition && capability.Domain != "binary_sensor" {
		return []string{fmt.Sprintf("%s: %q's \"condition\" derivation must be a \"binary_sensor\" capability, not %q -- use \"value\" instead for a non-boolean domain", provenance, label, capability.Domain)}, false
	}
	if capability.IsDerivedValue && capability.Domain == "binary_sensor" {
		return []string{fmt.Sprintf("%s: %q's \"value\" derivation may not be a \"binary_sensor\" capability -- use \"condition\" instead", provenance, label)}, false
	}

	tree := capability.DerivedCondition
	if capability.IsDerivedValue {
		tree = capability.DerivedValue
	}
	if tree == nil {
		return []string{fmt.Sprintf("%s: logical device %q's %q derivation has no expression to resolve", provenance, decl.DeviceID, label)}, false
	}

	resolver := &logicalConditionResolver{
		administration:        administration,
		deviceID:              decl.DeviceID,
		label:                 label,
		provenance:            provenance,
		finalAttempt:          finalAttempt,
		discoveryGatewaysByID: discoveryGatewaysByID,
		hassBridgeDevicesByID: hassBridgeDevicesByID,
		importedDevicesByID:   importedDevicesByID,
		hostDevicesByID:       hostDevicesByID,
		localDevicesByID:      localDevicesByID,
		logicalDevicesByID:    logicalDevicesByID,
		valueMode:             capability.IsDerivedValue,
	}
	rendered, ok := resolver.render(tree)
	if !ok {
		if resolver.deferred {
			return nil, true
		}
		return resolver.warnings, false
	}

	fullName := resolveDeviceEntityFullName(decl.LocalSpec, administration.SpacePath, deviceNamePath)
	identity := extractEntityIdentity(fullName)
	if identity.Domain == "" {
		return []string{fmt.Sprintf("%s: could not resolve a domain from %q; skipping", provenance, decl.LocalSpec)}, false
	}
	entityID := toHomeAssistantEntityID(fullName)
	if entityID == "" {
		return []string{fmt.Sprintf("%s: could not resolve a Home Assistant entity id from %q; skipping", provenance, decl.LocalSpec)}, false
	}

	deviceClass := capability.DerivedDeviceClass
	if deviceClass == "" {
		deviceClass, _, _, _ = resolveCapabilityDefaults(administration.CapabilityDefaults, identity.Domain, identity.Path)
	}

	spaceName := administration.CurrentSpaceName()
	administration.AppendEntityRecord(spaceName, TEntityRecord{
		Name:                  fullName,
		Identity:              identity,
		Provenance:            provenance,
		ConditionExpr:         rendered,
		ConditionDevClass:     deviceClass,
		ConditionDelayOn:      capability.DelayOn,
		ConditionDelayOff:     capability.DelayOff,
		HasDefinitionOrImport: true,
	})
	administration.LogicalEntityLinks[entityID] = TLogicalEntityLink{DeviceID: decl.DeviceID, Label: label}
	return nil, false
}
