###
#
# Generation of HASS configurations for REST-based imports
#
###

function ImportRESTEntityDefinition { # $1 = REST bridge, $2 = REST source, $3 = REST frequency, $4 = REST statety
  ReadFile $HASSRESTBridges $1 $ConfigFile
  
  AddToFile "CheckEntity $HASSFullName $RESTUrl/$2 $RESTAuthorization" $CheckEntities

  if [ "$4" == "" ]; then
    State="value_json.state"
  else
    State="$(InsertStateInCondition "$4" "value_json.state")"
  fi
  
  define
    Body      "platform: rest"
    Body      "resource: $RESTUrl/$2"
    Body      "name: $FriendlyName"
    Body      "value_template: \"{{ $State }}\""
    Body      "unique_id: $HASSFullName"
    BodyIfStr "unit_of_measurement: " "$Units"
    BodyIf    "device_class: " "$DeviceClass"
    BodyIf    "state_class: " "$StateClass"
    BodyIf    "icon: " "$Icon"
    Body      "scan_interval: $3"
    Body      "headers:"
    Body      "  authorization: $RESTAuthorization"
    Body      "  content-type: \"application/json\""
}
