#!/bin/bash

echo Generalize Update script

rsync -arv --delete -e "ssh -p 1967" hass/junglinster hassio@junglinster.homelinux.org:.
for e in configuration.yaml automation entities customization integrations script; do
  ssh hassio@junglinster.homelinux.org -p 1967 sudo rsync -arv --delete /home/hassio/junglinster/$e /root/config
done
for e in automation script; do
  ssh hassio@junglinster.homelinux.org -p 1967 sudo "ln -sf /config/${e}s.yaml /config/$e/"
done
